project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "LSU-AGRO4092: R for Spatial Analysis & Visualization"
  author:
    - Vinit Sehgal, Ph.D. (Louisiana State University)
  repo-url: https://github.com/vinit-sehgal/AGRO4092
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd

format:
  html:
    theme: united
    rmdformats::readthedown:
    code-fold: false
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango


