project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "R for Spatial Analysis & Visualization"
  author:
    - Vinit Sehgal, Ph.D.
  repo-url: https://github.com/vinit-sehgal/AGRO4092
  date: "Jan-16-2024"
  page-footer:
    right: |
      Class Notes for AGRO-4092 at <a href="https://www.lsu.edu/">Louisiana State University</a>
  #repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - ch9.qmd
    - chN.qmd

format:
  html:
    theme: flatly
    rmdformats::readthedown:
    code-fold: false
    self_contained: true
    toc: true
    thumbnails: true
    lightbox: true
    gallery: true
    highlight: tango


